apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoint-health-checker
  labels:
    app: endpoint-health-checker
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/status", "services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"] 