apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: endpoint-health-checker
  labels:
    app: endpoint-health-checker
subjects:
  - kind: ServiceAccount
    name: endpoint-health-checker
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: endpoint-health-checker
  apiGroup: rbac.authorization.k8s.io 