namespace: kube-system
replicaCount: 3
# Master nodes IPs (optional, auto-detected if not specified)
MASTER_NODES: ""
global:
  nodeSelector:
    kubernetes.io/os: linux
  registry:
    address: docker.io
    imagePullSecrets: []
  images:
    endpoint_health_checker:
      repository: kubeovn/endpoint-health-checker
      tag: v0.1.1
      pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
    endpointHealthChecker:
      tag: v0.0.0-beta.24.g5ff721c3
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: endpoint-health-checker
        topologyKey: "kubernetes.io/hostname"
logLevel: 2
## Theoretical maximum failover time: healthCheckInterval + healthCheckProbeTimeout * healthCheckRetryCount
## Health check polling interval
healthCheckInterval: 1s
## Health check concurrency
healthCheckConcurrency: 10
## Health check probe timeout
healthCheckProbeTimeout: 1s
## Health check retry count
healthCheckRetryCount: 10
## Leader election configuration
leaderElection:
  ## Lease lock name
  leaseName: "endpoint-health-checker-leader"
  ## Lease duration
  leaseDuration: 4s
  ## Renew deadline
  renewDeadline: 2s
  ## Retry period
  retryPeriod: 500ms
